version: '3'

services:
  web:
    build: .
    command: bash -c "python app.py runserver 0.0.0.0:8000"
    container_name: stock-tracker
    volumes:
      - .:/stock-tracker
    ports:
- "8000:8000"